[[redirects]]
from = "https://jay-business.netlify.app/*"
to = "https://www.jaybittner.com/:splat"
status = 301
force = true

[[redirects]]
from = "http://www.jaybittner.com/*"
to = "https://www.jaybittner.com/:splat"
status = 301
force = true

[[redirects]]
from = "http://jaybittner.com/*"
to = "https://www.jaybittner.com/:splat"
status = 301
force = true